# Generated by Django 4.0.1 on 2022-01-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_ordermodel_city_ordermodel_email_ordermodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
