# Generated by Django 4.0.1 on 2022-01-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_ordermodel_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_shippped',
            field=models.BooleanField(default=False),
        ),
    ]
