# Generated by Django 4.0.1 on 2022-01-30 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_menuitem_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='added',
        ),
    ]
