# Generated by Django 4.0.1 on 2022-01-30 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_menuitem_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='added',
            new_name='created_on',
        ),
    ]
