# Generated by Django 4.0.1 on 2022-01-30 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_rename_added_menuitem_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='created_on',
        ),
    ]
